# fly.toml app configuration file generated for tang-reactivities on 2023-12-19T23:58:26+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tang-reactivities"
primary_region = "sin"

[build]
  image = "houxian/reactivities"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dq97e8voy"
  Cloudinary__AoiKey="823339294265466"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
